import SidebarLayout from '@/layouts/SidebarLayout/SidebarLayout';
import Head from 'next/head';
import { ReactElement } from 'react';
import {
  Chart as ChartJS,
  ArcElement,
  Tooltip,
  Legend,
  ChartData,
  ChartOptions,
} from 'chart.js';
import { Doughnut } from 'react-chartjs-2';

ChartJS.register(ArcElement, Tooltip, Legend);

const chartData: ChartData<'doughnut', number[], string> = {
  labels: ['Red', 'Green', 'Yellow'],
  datasets: [
    {
      data: [300, 50, 100],
      backgroundColor: ['#FF6384', '#36A2EB', '#FFCE56'],
      hoverBackgroundColor: ['#FF6384', '#36A2EB', '#FFCE56'],
    },
  ],
};

const chartOptions: ChartOptions<'doughnut'> = {
  plugins: {
    legend: {
      display: false,
    },
  },
};

const Home = () => {
  return (
    <>
      <Head>
        <title>AidLog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>
        <h2 className="text-sm uppercase font-semibold text-gray-600">
          Bağış İstatistikleri
        </h2>

        <div className="mt-4">
          <dl className="grid grid-cols-1 gap-5 sm:grid-cols-3">
            <div className="px-4 py-5 bg-white shadow rounded-lg overflow-hidden sm:p-6">
              <dt className="text-sm font-medium text-gray-500 truncate">
                Title
              </dt>
              <dd className="mt-1 text-3xl font-semibold text-gray-900">
                1.000
              </dd>
            </div>

            <div className="px-4 py-5 bg-white shadow rounded-lg overflow-hidden sm:p-6">
              <dt className="text-sm font-medium text-gray-500 truncate">
                Title
              </dt>
              <dd className="mt-1 text-3xl font-semibold text-gray-900">
                1.000
              </dd>
            </div>

            <div className="px-4 py-5 bg-white shadow rounded-lg overflow-hidden sm:p-6">
              <dt className="text-sm font-medium text-gray-500 truncate">
                Title
              </dt>
              <dd className="mt-1 text-3xl font-semibold text-gray-900">
                1.000
              </dd>
            </div>

            <div className="px-4 py-5 bg-white shadow rounded-lg overflow-hidden sm:p-6">
              <dt className="text-sm font-medium text-gray-500 truncate">
                Title
              </dt>
              <dd className="mt-1 text-3xl font-semibold text-gray-900">
                1.000
              </dd>
            </div>

            <div className="px-4 py-5 bg-white shadow rounded-lg overflow-hidden sm:p-6">
              <dt className="text-sm font-medium text-gray-500 truncate">
                Title
              </dt>
              <dd className="mt-1 text-3xl font-semibold text-gray-900">
                1.000
              </dd>
            </div>

            <div className="px-4 py-5 bg-white shadow rounded-lg overflow-hidden sm:p-6">
              <dt className="text-sm font-medium text-gray-500 truncate">
                Title
              </dt>
              <dd className="mt-1 text-3xl font-semibold text-gray-900">
                1.000
              </dd>
            </div>
          </dl>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-3 gap-5 mt-5">
          <div className="px-4 py-5 bg-white shadow rounded-lg overflow-hidden sm:p-6">
            <dt className="text-sm font-medium text-gray-500 truncate">
              Title
            </dt>

            <dd className="mt-1">
              <Doughnut
                options={chartOptions}
                data={chartData}
                width="auto"
                height="auto"
              />
            </dd>
          </div>

          <div className="px-4 py-5 bg-white shadow rounded-lg overflow-hidden sm:p-6">
            <dt className="text-sm font-medium text-gray-500 truncate">
              Title
            </dt>

            <dd className="mt-1">
              <Doughnut
                options={chartOptions}
                data={chartData}
                width="auto"
                height="auto"
              />
            </dd>
          </div>

          <div className="px-4 py-5 bg-white shadow rounded-lg overflow-hidden sm:p-6">
            <dt className="text-sm font-medium text-gray-500 truncate">
              Title
            </dt>

            <dd className="mt-1">
              <Doughnut
                options={chartOptions}
                data={chartData}
                width="auto"
                height="auto"
              />
            </dd>
          </div>
        </div>
      </section>
    </>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return <SidebarLayout title="Panel">{page}</SidebarLayout>;
};

export default Home;
