import SidebarLayout from '@/layouts/SidebarLayout/SidebarLayout';
import Head from 'next/head';
import { ReactElement } from 'react';

const Home = () => {
  return (
    <>
      <Head>
        <title>AidLog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <section>Dashboard content</section>
    </>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return <SidebarLayout title="Dashboard">{page}</SidebarLayout>;
};

export default Home;
